contacts/urls.py
from django.contrib.auth import views as auth_views
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.views import serve


urlpatterns = [
    url(r'^', include('website.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/login/$',
        auth_views.login,
        {'template_name': 'website/login.html'}
        ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ]

website/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(
        r'^$',
        views.index,
        name='index'
    ),
    url(
        r'^create-account/$',
        views.create_account,
        name='create_account'
    ),
    url(
        r'^logout/$',
        views.logout_view,
        name='logout'
    ),
    url(
        r'^contacts/new/$',
        views.edit_contact,
        name='new_contact'
    ),
    url(
        r'^contacts/edit/(\d+)/$',
        views.edit_contact,
        name='edit_contact'
    ),
    url(
        r'^groups/$',
        views.groups_overview,
        name='groups_overview'
    ),
    url(
        r'^groups/new/$',
        views.edit_group,
        name='new_group'
    ),
    url(
        r'^groups/edit/(\d+)/$',
        views.edit_group,
        name='edit_group'
    ),
]

website/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Group(models.Model):
    """
    A contact Group, such as Family, Friends, Work...

    `user` stores the User that create this Group, in other words,
    this `Group` belongs to `user`.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('User'),
    )

    name = models.CharField(
        _('Group name'),
        max_length=64,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('Group')


class Contact(models.Model):
    """
    `Contact` is a simple class to store a contact with the fields:
        required fields: name, phone1
        optional fields: phone2, email, birthday

    `user` stores the User that create this Contact, in other words,
    this `Contact` belongs to `user`.
    """

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('User'),
    )

    name = models.CharField(
        _('Full name'),
        max_length=254,
    )

    phone1 = models.CharField(
        _('Phone 1'),
        max_length=28,
    )

    phone2 = models.CharField(
        _('Phone 2'),
        max_length=28,
        blank=True,
        null=True,
    )

    email = models.EmailField(
        _('E-mail'),
        blank=True,
        null=True,
    )

    birthday = models.DateField(
        _('Birthday'),
        blank=True,
        null=True,
    )

    groups = models.ManyToManyField(
        Group,
        verbose_name=_('Groups'),
        related_name='groups_set',
        blank=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _('User')

website/forms.py
from django import forms
from .models import Contact, Group
from django.contrib.auth import get_user_model
from django.utils.translation import ugettext_lazy as _


class CreateAccountForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'password']

        widgets = {
            'password': forms.PasswordInput(attrs={'required': True}),
        }

    def save(self, commit=True):
        if self.errors:
            raise ValueError(_('Invalid data'))
        instance = get_user_model().objects.create_user(**self.cleaned_data)
        return instance


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        exclude = ['user']


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        exclude = ['user']

website/views.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.utils.translation import ugettext_lazy as _
from .forms import CreateAccountForm, ContactForm, GroupForm
from .models import Contact, Group
from django.db.models.functions import Lower


def commom_cud(request, form_class, model_class, pk):
    '''
    Commom CUD is a function with the commom operations on the views for
    Create, Update and Delete.

    @request     = request
    @form_class  = a class extended from `forms.Form`
    @model_class = a class extended from `models.Model`
    @pk          = a primary key for `model_class`

    Returns:
    [action, instance, form]
    @action   = What the user apparentry wants to do ('delete', 'update',
                'none'); In case of 'none' you can assume that
                `not request.method == 'POST'`, and 'create' is merged with
                'update'
    @instance = The instance of `model_class` with `pk=pk`
    @form     = The instance of `form_class` with `request.POST` data loaded
    '''

    # Check if the `model_class` have a instance with the `pk`. If so, it's
    # stored in `instance`, and `action` is set.
    try:
        instance = model_class.objects.get(pk=pk)
    except model_class.DoesNotExist:
        instance = None

    if request.method == 'POST':    # Form send

        # IF instance exists AND action == 'delete'
        if instance and 'delete' in request.POST:
            return ('delete', instance, None)

        # get the Form with the `request.POST` data, and link it to `instance`
        # if `not instance == None`
        form = form_class(request.POST, instance=instance)

        if form.is_valid():
            return ('update', instance, form)

    else:    # Regular GET
        form = form_class(instance=instance)

    return ('none', instance, form)


def create_account(request):
    if request.method == 'POST':
        form = CreateAccountForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, _('Account successfully created. '
                                        'Please login.'))
            return redirect('index')
    else:
        form = CreateAccountForm()

    context = {
        'form': form,
    }
    return render(request, 'website/create_account.html', context)


@login_required
def index(request):
    '''
    Lists contacts from the request user
    '''

    context = {
        'contacts': request.user.contact_set.order_by(Lower('name')),
    }
    return render(request, 'website/list_contacts.html', context)


@login_required
def edit_contact(request, pk=None):
    '''
    Creates a new contact, or edit a old one
    '''

    action, instance, form = commom_cud(request, ContactForm, Contact, pk)

    if action == 'delete':
        instance.delete()
        messages.warning(request, _("Contact successfully deleted"))
        return redirect('index')

    elif action == 'update':
        # Fake-save the form, so it creates a new instance (or reuse the
        # old one) with the data received by form.
        inst = form.save(commit=False)
        inst.user = request.user
        inst.save()  # Really save the instance
        form.save_m2m()  # Save the Many To Many Relationship

        messages.success(request, _("Contact successfully created"))
        return redirect('index')

    else:    # Regular GET
        choices = request.user.group_set.all()
        form.fields['groups'].choices = [(c.id, c.name) for c in choices]
        context = {
            'form': form,
            'instance': instance,
            'verbose_name': (Contact
                             ._meta.verbose_name.title())
        }
        return render(request, 'website/edit.html', context)


@login_required
def groups_overview(request):
    '''
    Lists groups from the request user
    '''

    context = {
        'groups': request.user.group_set.order_by(Lower('name')),
    }
    return render(request, 'website/list_groups.html', context)


@login_required
def edit_group(request, pk=None):
    '''
    Creates a new group, or edit a old one
    '''

    action, instance, form = commom_cud(request, GroupForm, Group, pk)

    if action == 'delete':
        instance.delete()
        messages.warning(request, _("Group successfully deleted"))
        return redirect('groups_overview')

    elif action == 'update':
        # Fake-save the form, so it creates a new instance (or reuse the
        # old one) with the data received by form.
        inst = form.save(commit=False)
        inst.user = request.user
        inst.save()  # Really save the instance

        messages.success(request, _("Group successfully created"))
        return redirect('groups_overview')

    else:    # Regular GET
        context = {
            'form': form,
            'instance': instance,
            'verbose_name': (Group
                             ._meta.verbose_name.title())
        }
        return render(request, 'website/edit.html', context)


def logout_view(request):
    logout(request)
    return redirect('index')

website/templates/website/base.html
{% load compress staticfiles %}

<!DOCTYPE html>
<html lang="pt">
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">

		<title>{% block title %}Contacts{% endblock %}</title>

		<!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"> -->
		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
		{% compress css %}
			<link href="{% static 'css/app.css' %}" rel="stylesheet" type="text/css" />
			{% block extracss %}{% endblock %}
		{% endcompress %}

		<!-- Chrome & Firefox OS (Android 5.0+) -->
		<meta name="theme-color" content="#095765">
		<!-- Windows Phone -->
		<meta name="msapplication-navbutton-color" content="#095765">
		{% block extrahead %}{% endblock %}
	</head>

	<body>
		<div id="home" class="navbar-fixed">
			<nav>
				<div class="nav-wrapper">
					<a href="{% if not is_home %}{% url 'index' %}{%else%}#home{%endif%}" class="brand-logo">
						<img src="{% static 'img/logo-dark-bg.png' %}"/>
					</a>
					<a href="#" data-activates="mobile-nav" class="button-collapse"><i class="material-icons reset">menu</i></a>
					<ul class="right hide-on-med-and-down">
						{% include 'website/links_topbar.html' %}
					</ul>
					<ul id="mobile-nav" class="side-nav mobile-nav">
						{% include 'website/links_topbar.html' %}
					</ul>

				</div>
			</nav>
		</div>

		<main>
			{% block base_content %}{% endblock %}
		</main>

		{% compress js %}
			<script src="{% static 'bower_components/jquery/dist/jquery.js' %}"></script>
			<script src="{% static 'bower_components/Materialize/bin/materialize.js' %}"></script>
			<script src="{% static 'js/app.js' %}"></script>
		{% endcompress %}
		{% block extrajs %}{% endblock %}
	</body>
</html>

website/templates/website/create_account.html
{% extends 'website/base.html' %}

{% load staticfiles i18n %}

{% block base_content %}
<div class="row container">
	<div class="s12 m10 l8 offset-m1 offset-l2 col">
		{% include 'renders/render_messages.html' %}
		<h4>{% trans 'Create Account' %}</h4>
		<form method="post">
			{% csrf_token %}
			{% include 'renders/render_form.html' with form=form %}
			<div class="row">
				<div class="s12 col">
					<button class="right waves-effect waves-light btn-large black-text" type="submit" name="action">{% trans 'Create Account' %}</button>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

website/templates/website/edit.html
{% extends 'website/base.html' %}

{% load staticfiles i18n %}

{% block base_content %}
<div class="row container">
	<div class="s12 m12 l8 offset-l2 col">
		{% include 'renders/render_messages.html' %}

		<h4>
		{% if form.instance.pk %}
			{% trans 'Edit' %}
		{% else %}
			{% trans 'New' %}
		{% endif %} {{verbose_name}}
		</h4>

		<form method="post">
			{% csrf_token %}
			{% include 'renders/render_form.html' with form=form %}
			<div class="row">
				{% if form.instance.pk %}
				<div class="s6 col">
					<button class="waves-effect waves-light btn-large black-text red" name="delete">{% trans 'Delete' %}</button>
				</div>
				{% endif %}
				<div class="{% if form.instance.pk %}s6{% else %}s12{% endif %} col">
					<button class="right waves-effect waves-light btn-large black-text" type="submit" name="action">{% trans 'Save' %}</button>
				</div>
			</div>
		</form>
	</div>
</div>
{% endblock %}

{% block extrajs %}
<script type="text/javascript">
$(document).ready(function() {
	$('select[multiple=multiple]').prepend('<option value="" disabled selected>{% trans "Chose groups" %}</option>').material_select();
	var $input = $('#id_birthday').pickadate({
		format: 'mm/dd/yyyy',
		today: '',
		clear: '{% trans "Clear" %}',
		close: '{% trans "Close" %}',
		selectMonths: true,
		selectYears: 100,
		yearRange: "-100:+0",
		max: new Date,
	});
	var picker = $input.pickadate('picker');
	$input.click(function() {
		picker.open();
	})

	// Desabilita a edicao manual do input
	$('#id_birthday').prop("readonly", true);

	$('[name="delete"]').click(function() {
		return confirm('{% trans "are you sure you want to delete?" %}');
	});
});
</script>
{% endblock %}

website/templates/website/links_topbar.html
{% load i18n %}

{% if user.is_authenticated %}
<li><a href="{% url 'index' %}">{% trans 'Contacts' %}</a></li>
<li><a href="{% url 'groups_overview' %}">{% trans 'Groups' %}</a></li>
<li><a href="{% url 'logout' %}">{% trans 'Logout' %}</a></li>
{% endif %}

website/templates/website/list_contacts.html
{% extends 'website/base.html' %}

{% load staticfiles i18n %}

{% block base_content %}
<div class="row container">
	<div class="s12 col">
		{% include 'renders/render_messages.html' %}
		<h4>{% trans 'Contacts' %}</h4>
		<p><a href="{% url 'new_contact' %}" class="btn-flat waves-effect">
				<i class="material-icons">add</i>{% trans 'New Contact' %}
			</a>
		</p>
		<ul class="collapsible popout" data-collapsible="accordion">
		{% for contact in contacts %}
			<li>
				<div class="collapsible-header">{{contact.name}}</div>
				<div class="collapsible-body">
					<p>
						<b>{% trans 'Name' %}:</b> {{contact.name}}<br/>
						<b>{% trans 'Phone' %} 1:</b> {{contact.phone1}}<br/>
						{% if contact.phone2 %}<b>{% trans 'Phone' %} 2:</b> {{contact.phone2}}<br/>{% endif %}
						{% if contact.email %}<b>{% trans 'Email' %}:</b> {{contact.email}}<br/>{% endif %}
						{% if contact.birthday %}<b>{% trans 'Birthday' %}:</b> {{contact.birthday}}<br/>{% endif %}
						{% if contact.groups.all %}
							<b>{% trans 'Groups' %}:</b>
							 {% for group in contact.groups.all %}
								{{group.name}}{% if not forloop.last %}, {% endif %}
							{% endfor %}<br/>
						{% endif %}
						<a href="{% url 'edit_contact' contact.pk %}" class="btn waves-effect black-text"><i class="material-icons">edit</i>{% trans 'Edit' %}</a>
					</p>
				</div>
			</li>
		{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}

website/templates/website/list_groups.html
{% extends 'website/base.html' %}

{% load staticfiles i18n %}

{% block base_content %}
<div class="row container">
	<div class="s12 col">
		{% include 'renders/render_messages.html' %}
		<h4>{% trans 'Groups' %}</h4>
		<p><a href="{% url 'new_group' %}" class="btn-flat waves-effect">
				<i class="material-icons">add</i>{% trans 'New Groups' %}
			</a>
		</p>
		<ul class="collection">
		{% for group in groups %}
			<li class="collection-item">
				<a href="{% url 'edit_group' group.pk %}" class="btn-flat waves-effect black-text">
					<i class="material-icons">edit</i>
				</a>{{group.name}}
			</li>
		{% endfor %}
		</ul>
	</div>
</div>
{% endblock %}

website/templates/website/login.html
{% extends 'website/base.html' %}

{% load staticfiles i18n %}

{% block base_content %}
<div class="row container">
	<div class="s12 col center">
		{% include 'renders/render_messages.html' %}
		<h2>Contacts</h2>
		<img src="{% static 'img/logo-img.png' %}">
	</div>
	<div class="s12 m8 l6 offset-m2 offset-l3 col">
		<form method="post">
		{% csrf_token %}
		{% include 'renders/render_form.html' with form=form %}
		<div class="row">
			<div class="s6 col">
				<a class="left waves-effect waves-light btn-large black-text blue" href="{% url 'create_account' %}">{% trans 'Create account' %}</a>
			</div>
			<div class="s6 col">
				<button class="right waves-effect waves-light btn-large black-text" type="submit" name="action">{% trans 'Login' %}</button>
			</div>
		</div>


		</form>
	</div>
</div>
{% endblock %}